export const eventData = {
  next_event : [
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    }
  ],
  past_event : [
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    },
    {
        "type": "Lecture",
        "title": "The Story of India's Unicorns",
        "venue": "Mumbai",
        "date": "Friday, August 31, 2019 ",
        "time": "6.00 to 7.30 pm",
        "description": "A lecture by Divyabhanusinh, Asok Kumar Das, and Shibani Bose to celebrate the release of The Story of India's Unicorns",
    }
  ]
};
